CREATE TABLE staff_qualifications (
    id VARCHAR NOT NULL PRIMARY KEY,
    staff_id VARCHAR NOT NULL,
    degree VARCHAR NOT NULL,
    institution VARCHAR NOT NULL,
    year_of_completion INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (staff_id) REFERENCES staff (id) ON DELETE CASCADE
);