CREATE TABLE student_attendance (
    id VARCHAR NOT NULL PRIMARY KEY,
    student_id VARCHAR NOT NULL,
    class_id VARCHAR NOT NULL,
    date DATE NOT NULL,
    status VARCHAR NOT NULL,
    marked_by VARCHAR NOT NULL,
    remarks VARCHAR,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);