// This file is auto-generated by @hey-api/openapi-ts

import { infiniteQueryOptions, queryOptions } from '@tanstack/react-query'
import type {
  DefaultError,
  InfiniteData,
  UseMutationOptions,
} from '@tanstack/react-query'

import type {
  CreateStudentData,
  CreateStudentResponse,
  DeleteStudentData,
  DeleteStudentResponse,
  GetAllStudentsData,
  GetAllStudentsResponse,
  GetStudentByIdData,
  GetStudentByIdResponse,
  UpdateStudentData,
  UpdateStudentResponse,
} from '@/lib/api/types.gen'
import type { Options } from '@/lib/api/sdk.gen'
import { client } from '@/lib/api/client.gen'
import {
  createStudent,
  deleteStudent,
  getAllStudents,
  getStudentById,
  updateStudent,
} from '@/lib/api/sdk.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

// getAllStudents
export const getAllStudentsQueryKey = (options?: Options<GetAllStudentsData>) =>
  createQueryKey('getAllStudents', options)
export const getAllStudentsOptions = (options?: Options<GetAllStudentsData>) =>
  queryOptions<
    GetAllStudentsResponse,
    DefaultError,
    GetAllStudentsResponse,
    ReturnType<typeof getAllStudentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllStudents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAllStudentsQueryKey(options),
  })
export const getAllStudentsInfiniteQueryKey = (
  options?: Options<GetAllStudentsData>,
): QueryKey<Options<GetAllStudentsData>> =>
  createQueryKey('getAllStudents', options, true)
export const getAllStudentsInfiniteOptions = (
  options?: Options<GetAllStudentsData>,
) =>
  infiniteQueryOptions<
    GetAllStudentsResponse,
    DefaultError,
    InfiniteData<GetAllStudentsResponse>,
    QueryKey<Options<GetAllStudentsData>>,
    | number
    | null
    | Pick<
        QueryKey<Options<GetAllStudentsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAllStudentsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getAllStudents({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getAllStudentsInfiniteQueryKey(options),
    },
  )

// createStudent
export const createStudentMutation = (
  options?: Partial<Options<CreateStudentData>>,
): UseMutationOptions<
  CreateStudentResponse,
  DefaultError,
  Options<CreateStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateStudentResponse,
    DefaultError,
    Options<CreateStudentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createStudent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

// deleteStudent
export const deleteStudentMutation = (
  options?: Partial<Options<DeleteStudentData>>,
): UseMutationOptions<
  DeleteStudentResponse,
  DefaultError,
  Options<DeleteStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteStudentResponse,
    DefaultError,
    Options<DeleteStudentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteStudent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

// getStudentById
export const getStudentByIdQueryKey = (options: Options<GetStudentByIdData>) =>
  createQueryKey('getStudentById', options)
export const getStudentByIdOptions = (options: Options<GetStudentByIdData>) =>
  queryOptions<
    GetStudentByIdResponse,
    DefaultError,
    GetStudentByIdResponse,
    ReturnType<typeof getStudentByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStudentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getStudentByIdQueryKey(options),
  })

// updateStudent
export const updateStudentMutation = (
  options?: Partial<Options<UpdateStudentData>>,
): UseMutationOptions<
  UpdateStudentResponse,
  DefaultError,
  Options<UpdateStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateStudentResponse,
    DefaultError,
    Options<UpdateStudentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateStudent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
