// This file is auto-generated by @hey-api/openapi-ts

import { infiniteQueryOptions, queryOptions } from '@tanstack/react-query'
import type {
  DefaultError,
  InfiniteData,
  UseMutationOptions,
} from '@tanstack/react-query'

import type {
  CreateStudentData,
  CreateStudentResponse,
  DeleteStudentData,
  DeleteStudentResponse,
  GetAllStudentsData,
  GetAllStudentsResponse,
  GetStudentByIdData,
  GetStudentByIdResponse,
  UpdateStudentData,
  UpdateStudentResponse,
} from '@/lib/api/types.gen'
import type { Options } from '@/lib/api/sdk.gen'
import { client } from '@/lib/api/client.gen'
import {
  createStudent,
  deleteStudent,
  getAllStudents,
  getStudentById,
  updateStudent,
} from '@/lib/api/sdk.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  }
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

const createInfiniteParams = (
  queryKey: QueryKey<Options<GetAllStudentsData>>,
  page: Pick<QueryKey<Options<GetAllStudentsData>>[0], 'headers' | 'query'>,
): Pick<QueryKey<Options<GetAllStudentsData>>[0], 'headers' | 'query'> => {
  const baseParams = queryKey[0]

  return {
    headers:
      baseParams.headers || page.headers
        ? {
            ...(typeof baseParams.headers === 'object' &&
            baseParams.headers !== null
              ? baseParams.headers
              : {}),
            ...(typeof page.headers === 'object' && page.headers !== null
              ? page.headers
              : {}),
          }
        : undefined,
    query:
      baseParams.query || page.query
        ? {
            ...(typeof baseParams.query === 'object' &&
            baseParams.query !== null
              ? baseParams.query
              : {}),
            ...(typeof page.query === 'object' && page.query !== null
              ? page.query
              : {}),
          }
        : undefined,
  }
}

// getAllStudents
export const getAllStudentsQueryKey = (options?: Options<GetAllStudentsData>) =>
  createQueryKey('getAllStudents', options)
export const getAllStudentsOptions = (options?: Options<GetAllStudentsData>) =>
  queryOptions<
    GetAllStudentsResponse,
    DefaultError,
    GetAllStudentsResponse,
    ReturnType<typeof getAllStudentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllStudents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAllStudentsQueryKey(options),
  })
export const getAllStudentsInfiniteQueryKey = (
  options?: Options<GetAllStudentsData>,
): QueryKey<Options<GetAllStudentsData>> =>
  createQueryKey('getAllStudents', options, true)
export const getAllStudentsInfiniteOptions = (
  options?: Options<GetAllStudentsData>,
) =>
  infiniteQueryOptions<
    GetAllStudentsResponse,
    DefaultError,
    InfiniteData<GetAllStudentsResponse>,
    QueryKey<Options<GetAllStudentsData>>,
    | number
    | null
    | Pick<QueryKey<Options<GetAllStudentsData>>[0], 'headers' | 'query'>
  >({
    queryFn: async ({ pageParam, queryKey, signal }) => {
      const page: Pick<
        QueryKey<Options<GetAllStudentsData>>[0],
        'headers' | 'query'
      > =
        typeof pageParam === 'object' && pageParam !== null
          ? pageParam
          : {
              query: {
                page: pageParam,
              },
            }
      const params = createInfiniteParams(queryKey, page)
      const { data } = await getAllStudents({
        ...options,
        ...params,
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAllStudentsInfiniteQueryKey(options),
    initialPageParam: 1,
    getNextPageParam: (lastPage) =>
      lastPage.page < lastPage.total_pages ? lastPage.page + 1 : undefined,
  })

// createStudent
export const createStudentMutation = (
  options?: Partial<Options<CreateStudentData>>,
): UseMutationOptions<
  CreateStudentResponse,
  DefaultError,
  Options<CreateStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateStudentResponse,
    DefaultError,
    Options<CreateStudentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createStudent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

// deleteStudent
export const deleteStudentMutation = (
  options?: Partial<Options<DeleteStudentData>>,
): UseMutationOptions<
  DeleteStudentResponse,
  DefaultError,
  Options<DeleteStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteStudentResponse,
    DefaultError,
    Options<DeleteStudentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteStudent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

// getStudentById
export const getStudentByIdQueryKey = (options: Options<GetStudentByIdData>) =>
  createQueryKey('getStudentById', options)
export const getStudentByIdOptions = (options: Options<GetStudentByIdData>) =>
  queryOptions<
    GetStudentByIdResponse,
    DefaultError,
    GetStudentByIdResponse,
    ReturnType<typeof getStudentByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStudentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getStudentByIdQueryKey(options),
  })

// updateStudent
export const updateStudentMutation = (
  options?: Partial<Options<UpdateStudentData>>,
): UseMutationOptions<
  UpdateStudentResponse,
  DefaultError,
  Options<UpdateStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateStudentResponse,
    DefaultError,
    Options<UpdateStudentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateStudent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
