// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '@/lib/api/client.gen';
import {
  getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1,
  postStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1,
  deleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855,
  getStudents4D5Cba944Bd069Fdf2A0246F5Bac2855,
  putStudents4D5Cba944Bd069Fdf2A0246F5Bac2855,
  getStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030A,
  getStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6,
  postStudents87F142Fffc2984E3Ceb560Aac590Bf2A,
} from '@/lib/api/sdk.gen';
import type {
  GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data,
  GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Response,
  PostStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data,
  PostStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Response,
  DeleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data,
  DeleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response,
  GetStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data,
  GetStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response,
  PutStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data,
  PutStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response,
  GetStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030aData,
  GetStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030aResponse,
  GetStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6Data,
  GetStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6Response,
  PostStudents87F142Fffc2984E3Ceb560Aac590Bf2aData,
  PostStudents87F142Fffc2984E3Ceb560Aac590Bf2aResponse,
} from '@/lib/api/types.gen';
import type { Options } from '@/lib/api/sdk.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...queryKey[0].body as any,
      ...page.body as any
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers
    };
  }
  if (page.path) {
    params.path = {
      ...queryKey[0].path as any,
      ...page.path as any
    };
  }
  if (page.query) {
    params.query = {
      ...queryKey[0].query as any,
      ...page.query as any
    };
  }
  return params as unknown as typeof page;
};

// getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1
export const getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1QueryKey = (options?: Options<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>) => createQueryKey('getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1', options);
export const getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Options = (options?: Options<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>) => queryOptions<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Response, DefaultError, GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Response, ReturnType<typeof getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1QueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1QueryKey(options)
});
export const getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1InfiniteQueryKey = (options?: Options<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>): QueryKey<Options<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>> => createQueryKey('getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1', options, true);
export const getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1InfiniteOptions = (options?: Options<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>) => infiniteQueryOptions<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Response, DefaultError, InfiniteData<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Response>, QueryKey<Options<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>>, number | null | Pick<QueryKey<Options<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>>[0], 'body' | 'headers' | 'path' | 'query'>>(
  // @ts-ignore
  {
    queryFn: async ({ pageParam, queryKey, signal }) => {
      // @ts-ignore
      const page: Pick<QueryKey<Options<GetStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
        query: {
          page: pageParam
        }
      };
      const params = createInfiniteParams(queryKey, page);
      const { data } = await getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1({
        ...options,
        ...params,
        signal,
        throwOnError: true
      });
      return data;
    },
    queryKey: getStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1InfiniteQueryKey(options)
  });

// postStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1
export const postStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Mutation = (options?: Partial<Options<PostStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>>): UseMutationOptions<PostStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Response, DefaultError, Options<PostStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>> => {
  const mutationOptions: UseMutationOptions<PostStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Response, DefaultError, Options<PostStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1Data>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postStudents9Cfb76Aa83C6A83D99Db1D6755C24Ee1({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

// deleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855
export const deleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Mutation = (options?: Partial<Options<DeleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data>>): UseMutationOptions<DeleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response, DefaultError, Options<DeleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data>> => {
  const mutationOptions: UseMutationOptions<DeleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response, DefaultError, Options<DeleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteStudents4D5Cba944Bd069Fdf2A0246F5Bac2855({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

// getStudents4D5Cba944Bd069Fdf2A0246F5Bac2855
export const getStudents4D5Cba944Bd069Fdf2A0246F5Bac2855QueryKey = (options: Options<GetStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data>) => createQueryKey('getStudents4D5Cba944Bd069Fdf2A0246F5Bac2855', options);
export const getStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Options = (options: Options<GetStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data>) => queryOptions<GetStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response, DefaultError, GetStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response, ReturnType<typeof getStudents4D5Cba944Bd069Fdf2A0246F5Bac2855QueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getStudents4D5Cba944Bd069Fdf2A0246F5Bac2855({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getStudents4D5Cba944Bd069Fdf2A0246F5Bac2855QueryKey(options)
});

// putStudents4D5Cba944Bd069Fdf2A0246F5Bac2855
export const putStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Mutation = (options?: Partial<Options<PutStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data>>): UseMutationOptions<PutStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response, DefaultError, Options<PutStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data>> => {
  const mutationOptions: UseMutationOptions<PutStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Response, DefaultError, Options<PutStudents4D5Cba944Bd069Fdf2A0246F5Bac2855Data>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await putStudents4D5Cba944Bd069Fdf2A0246F5Bac2855({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};

// getStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030A
export const getStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030AQueryKey = (options?: Options<GetStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030aData>) => createQueryKey('getStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030A', options);
export const getStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030AOptions = (options?: Options<GetStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030aData>) => queryOptions<GetStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030aResponse, DefaultError, GetStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030aResponse, ReturnType<typeof getStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030AQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030A({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getStudentsSearch0F4D7Fb5A84E5A127E2Bc6232De9030AQueryKey(options)
});

// getStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6
export const getStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6QueryKey = (options?: Options<GetStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6Data>) => createQueryKey('getStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6', options);
export const getStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6Options = (options?: Options<GetStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6Data>) => queryOptions<GetStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6Response, DefaultError, GetStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6Response, ReturnType<typeof getStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6QueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getStudentsFilterC21054074427E0Dcf7272Dd5086Ce1F6QueryKey(options)
});

// postStudents87F142Fffc2984E3Ceb560Aac590Bf2A
export const postStudents87F142Fffc2984E3Ceb560Aac590Bf2AMutation = (options?: Partial<Options<PostStudents87F142Fffc2984E3Ceb560Aac590Bf2aData>>): UseMutationOptions<PostStudents87F142Fffc2984E3Ceb560Aac590Bf2aResponse, DefaultError, Options<PostStudents87F142Fffc2984E3Ceb560Aac590Bf2aData>> => {
  const mutationOptions: UseMutationOptions<PostStudents87F142Fffc2984E3Ceb560Aac590Bf2aResponse, DefaultError, Options<PostStudents87F142Fffc2984E3Ceb560Aac590Bf2aData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postStudents87F142Fffc2984E3Ceb560Aac590Bf2A({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};
