import type { PermissionEnum } from '@/lib/api/types.gen'

export const ALL_PERMISSION_ENUM_VALUES: Array<PermissionEnum> = [
  'UserCreate',
  'UserRead',
  'UserUpdate',
  'UserDelete',
  'UserManage',
  'UserManageRoles',
  'UserManagePermissions',
  'RoleCreate',
  'RoleRead',
  'RoleUpdate',
  'RoleDelete',
  'RoleManage',
  'RoleAssignPermissions',
  'PermissionCreate',
  'PermissionRead',
  'PermissionUpdate',
  'PermissionDelete',
  'PermissionManage',
  'PermissionSetManage',
  'StaffCreate',
  'StaffRead',
  'StaffUpdate',
  'StaffDelete',
  'StaffManage',
  'StaffManageAttendance',
  'StaffManageLeaves',
  'StudentCreate',
  'StudentRead',
  'StudentUpdate',
  'StudentDelete',
  'StudentManage',
  'StudentManageGuardians',
  'StudentManageEnrollment',
  'StudentManageAttendance',
  'StudentManageMarks',
  'AcademicYearManage',
  'TermManage',
  'GradeLevelManage',
  'ClassManage',
  'SubjectManage',
  'ClassSubjectTeacherManage',
  'TimetableManage',
  'ExamTypeManage',
  'ExamManage',
  'ExamSubjectManage',
  'GradingSchemeManage',
  'GradingCriterionManage',
  'LibraryManage',
  'CoCurricularManage',
  'ResourceCreate',
  'ResourceRead',
  'ResourceUpdate',
  'ResourceDelete',
  'ResourceBook',
  'ResourceViewBookings',
  'CurriculumCreate',
  'CurriculumRead',
  'CurriculumUpdate',
  'CurriculumDelete',
  'CurriculumManage',
  'SyllabusCreate',
  'SyllabusRead',
  'SyllabusUpdate',
  'SyllabusDelete',
  'SyllabusManage',
  'MessagingCreate',
  'MessagingRead',
  'MessagingUpdate',
  'MessagingDelete',
  'MessagingSend',
  'MessagingManage',
  'BehaviorIncidentTypeCreate',
  'BehaviorIncidentTypeRead',
  'BehaviorIncidentTypeUpdate',
  'BehaviorIncidentTypeDelete',
  'BehaviorIncidentRecord',
  'BehaviorIncidentRead',
  'BehaviorIncidentUpdate',
  'BehaviorIncidentDelete',
  'ViewFinancialReports',
  'SystemAdmin',
  'UserUpdateMedium',
  'UserDeleteSevere',
]

interface PermissionCategory {
  name: string
  permissions: Array<PermissionEnum>
}

export const PERMISSION_CATEGORIES: Array<PermissionCategory> = [
  {
    name: 'User Management',
    permissions: [
      'UserCreate',
      'UserRead',
      'UserUpdate',
      'UserDelete',
      'UserManage',
      'UserManageRoles',
      'UserManagePermissions',
      'UserUpdateMedium',
      'UserDeleteSevere',
    ],
  },
  {
    name: 'Role Management',
    permissions: [
      'RoleCreate',
      'RoleRead',
      'RoleUpdate',
      'RoleDelete',
      'RoleManage',
      'RoleAssignPermissions',
    ],
  },
  {
    name: 'Permission Management',
    permissions: [
      'PermissionCreate',
      'PermissionRead',
      'PermissionUpdate',
      'PermissionDelete',
      'PermissionManage',
      'PermissionSetManage',
    ],
  },
  {
    name: 'Staff Management',
    permissions: [
      'StaffCreate',
      'StaffRead',
      'StaffUpdate',
      'StaffDelete',
      'StaffManage',
      'StaffManageAttendance',
      'StaffManageLeaves',
    ],
  },
  {
    name: 'Student Management',
    permissions: [
      'StudentCreate',
      'StudentRead',
      'StudentUpdate',
      'StudentDelete',
      'StudentManage',
      'StudentManageGuardians',
      'StudentManageEnrollment',
      'StudentManageAttendance',
      'StudentManageMarks',
    ],
  },
  {
    name: 'Academic Management',
    permissions: [
      'AcademicYearManage',
      'TermManage',
      'GradeLevelManage',
      'ClassManage',
      'SubjectManage',
      'ClassSubjectTeacherManage',
      'TimetableManage',
    ],
  },
  {
    name: 'Exam Management',
    permissions: ['ExamTypeManage', 'ExamManage', 'ExamSubjectManage'],
  },
  {
    name: 'Grading Management',
    permissions: ['GradingSchemeManage', 'GradingCriterionManage'],
  },
  {
    name: 'Library Management',
    permissions: ['LibraryManage'],
  },
  {
    name: 'Co-Curricular Management',
    permissions: ['CoCurricularManage'],
  },
  {
    name: 'Resource Management',
    permissions: [
      'ResourceCreate',
      'ResourceRead',
      'ResourceUpdate',
      'ResourceDelete',
      'ResourceBook',
      'ResourceViewBookings',
    ],
  },
  {
    name: 'Curriculum Management',
    permissions: [
      'CurriculumCreate',
      'CurriculumRead',
      'CurriculumUpdate',
      'CurriculumDelete',
      'CurriculumManage',
    ],
  },
  {
    name: 'Syllabus Management',
    permissions: [
      'SyllabusCreate',
      'SyllabusRead',
      'SyllabusUpdate',
      'SyllabusDelete',
      'SyllabusManage',
    ],
  },
  {
    name: 'Messaging',
    permissions: [
      'MessagingCreate',
      'MessagingRead',
      'MessagingUpdate',
      'MessagingDelete',
      'MessagingSend',
      'MessagingManage',
    ],
  },
  {
    name: 'Behavior Management',
    permissions: [
      'BehaviorIncidentTypeCreate',
      'BehaviorIncidentTypeRead',
      'BehaviorIncidentTypeUpdate',
      'BehaviorIncidentTypeDelete',
      'BehaviorIncidentRecord',
      'BehaviorIncidentRead',
      'BehaviorIncidentUpdate',
      'BehaviorIncidentDelete',
    ],
  },
  {
    name: 'Financial Reports',
    permissions: ['ViewFinancialReports'],
  },
  {
    name: 'System Administration',
    permissions: ['SystemAdmin'],
  },
]
