/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminRbacRouteImport } from './routes/admin/rbac'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAcademicsRouteImport } from './routes/admin/academics'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authProfileRouteImport } from './routes/(auth)/profile'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AdminAttendanceStudentsRouteImport } from './routes/admin/attendance/students'
import { Route as AdminAttendanceStaffRouteImport } from './routes/admin/attendance/staff'
import { Route as AdminAcademicsYearsRouteImport } from './routes/admin/academics/years'
import { Route as AdminAcademicsTimetablesRouteImport } from './routes/admin/academics/timetables'
import { Route as AdminAcademicsTermsRouteImport } from './routes/admin/academics/terms'
import { Route as AdminAcademicsSubjectsRouteImport } from './routes/admin/academics/subjects'
import { Route as AdminAcademicsGradeLevelsRouteImport } from './routes/admin/academics/grade-levels'
import { Route as AdminAcademicsClassesRouteImport } from './routes/admin/academics/classes'
import { Route as AdminAcademicsClassAssignmentsRouteImport } from './routes/admin/academics/class-assignments'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicsRoute = AdminAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AdminRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authProfileRoute = authProfileRouteImport.update({
  id: '/(auth)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceStudentsRoute = AdminAttendanceStudentsRouteImport.update({
  id: '/attendance/students',
  path: '/attendance/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceStaffRoute = AdminAttendanceStaffRouteImport.update({
  id: '/attendance/staff',
  path: '/attendance/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicsYearsRoute = AdminAcademicsYearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => AdminAcademicsRoute,
} as any)
const AdminAcademicsTimetablesRoute =
  AdminAcademicsTimetablesRouteImport.update({
    id: '/timetables',
    path: '/timetables',
    getParentRoute: () => AdminAcademicsRoute,
  } as any)
const AdminAcademicsTermsRoute = AdminAcademicsTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AdminAcademicsRoute,
} as any)
const AdminAcademicsSubjectsRoute = AdminAcademicsSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminAcademicsRoute,
} as any)
const AdminAcademicsGradeLevelsRoute =
  AdminAcademicsGradeLevelsRouteImport.update({
    id: '/grade-levels',
    path: '/grade-levels',
    getParentRoute: () => AdminAcademicsRoute,
  } as any)
const AdminAcademicsClassesRoute = AdminAcademicsClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminAcademicsRoute,
} as any)
const AdminAcademicsClassAssignmentsRoute =
  AdminAcademicsClassAssignmentsRouteImport.update({
    id: '/class-assignments',
    path: '/class-assignments',
    getParentRoute: () => AdminAcademicsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof authLoginRoute
  '/profile': typeof authProfileRoute
  '/sign-up': typeof authSignUpRoute
  '/admin/academics': typeof AdminAcademicsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/academics/class-assignments': typeof AdminAcademicsClassAssignmentsRoute
  '/admin/academics/classes': typeof AdminAcademicsClassesRoute
  '/admin/academics/grade-levels': typeof AdminAcademicsGradeLevelsRoute
  '/admin/academics/subjects': typeof AdminAcademicsSubjectsRoute
  '/admin/academics/terms': typeof AdminAcademicsTermsRoute
  '/admin/academics/timetables': typeof AdminAcademicsTimetablesRoute
  '/admin/academics/years': typeof AdminAcademicsYearsRoute
  '/admin/attendance/staff': typeof AdminAttendanceStaffRoute
  '/admin/attendance/students': typeof AdminAttendanceStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/profile': typeof authProfileRoute
  '/sign-up': typeof authSignUpRoute
  '/admin/academics': typeof AdminAcademicsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/academics/class-assignments': typeof AdminAcademicsClassAssignmentsRoute
  '/admin/academics/classes': typeof AdminAcademicsClassesRoute
  '/admin/academics/grade-levels': typeof AdminAcademicsGradeLevelsRoute
  '/admin/academics/subjects': typeof AdminAcademicsSubjectsRoute
  '/admin/academics/terms': typeof AdminAcademicsTermsRoute
  '/admin/academics/timetables': typeof AdminAcademicsTimetablesRoute
  '/admin/academics/years': typeof AdminAcademicsYearsRoute
  '/admin/attendance/staff': typeof AdminAttendanceStaffRoute
  '/admin/attendance/students': typeof AdminAttendanceStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/profile': typeof authProfileRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/admin/academics': typeof AdminAcademicsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/academics/class-assignments': typeof AdminAcademicsClassAssignmentsRoute
  '/admin/academics/classes': typeof AdminAcademicsClassesRoute
  '/admin/academics/grade-levels': typeof AdminAcademicsGradeLevelsRoute
  '/admin/academics/subjects': typeof AdminAcademicsSubjectsRoute
  '/admin/academics/terms': typeof AdminAcademicsTermsRoute
  '/admin/academics/timetables': typeof AdminAcademicsTimetablesRoute
  '/admin/academics/years': typeof AdminAcademicsYearsRoute
  '/admin/attendance/staff': typeof AdminAttendanceStaffRoute
  '/admin/attendance/students': typeof AdminAttendanceStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/sign-up'
    | '/admin/academics'
    | '/admin/audit'
    | '/admin/rbac'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/users'
    | '/admin/'
    | '/admin/academics/class-assignments'
    | '/admin/academics/classes'
    | '/admin/academics/grade-levels'
    | '/admin/academics/subjects'
    | '/admin/academics/terms'
    | '/admin/academics/timetables'
    | '/admin/academics/years'
    | '/admin/attendance/staff'
    | '/admin/attendance/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/sign-up'
    | '/admin/academics'
    | '/admin/audit'
    | '/admin/rbac'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/users'
    | '/admin'
    | '/admin/academics/class-assignments'
    | '/admin/academics/classes'
    | '/admin/academics/grade-levels'
    | '/admin/academics/subjects'
    | '/admin/academics/terms'
    | '/admin/academics/timetables'
    | '/admin/academics/years'
    | '/admin/attendance/staff'
    | '/admin/attendance/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/(auth)/login'
    | '/(auth)/profile'
    | '/(auth)/sign-up'
    | '/admin/academics'
    | '/admin/audit'
    | '/admin/rbac'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/users'
    | '/admin/'
    | '/admin/academics/class-assignments'
    | '/admin/academics/classes'
    | '/admin/academics/grade-levels'
    | '/admin/academics/subjects'
    | '/admin/academics/terms'
    | '/admin/academics/timetables'
    | '/admin/academics/years'
    | '/admin/attendance/staff'
    | '/admin/attendance/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authProfileRoute: typeof authProfileRoute
  authSignUpRoute: typeof authSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academics': {
      id: '/admin/academics'
      path: '/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AdminAcademicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/profile': {
      id: '/(auth)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance/students': {
      id: '/admin/attendance/students'
      path: '/attendance/students'
      fullPath: '/admin/attendance/students'
      preLoaderRoute: typeof AdminAttendanceStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/staff': {
      id: '/admin/attendance/staff'
      path: '/attendance/staff'
      fullPath: '/admin/attendance/staff'
      preLoaderRoute: typeof AdminAttendanceStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academics/years': {
      id: '/admin/academics/years'
      path: '/years'
      fullPath: '/admin/academics/years'
      preLoaderRoute: typeof AdminAcademicsYearsRouteImport
      parentRoute: typeof AdminAcademicsRoute
    }
    '/admin/academics/timetables': {
      id: '/admin/academics/timetables'
      path: '/timetables'
      fullPath: '/admin/academics/timetables'
      preLoaderRoute: typeof AdminAcademicsTimetablesRouteImport
      parentRoute: typeof AdminAcademicsRoute
    }
    '/admin/academics/terms': {
      id: '/admin/academics/terms'
      path: '/terms'
      fullPath: '/admin/academics/terms'
      preLoaderRoute: typeof AdminAcademicsTermsRouteImport
      parentRoute: typeof AdminAcademicsRoute
    }
    '/admin/academics/subjects': {
      id: '/admin/academics/subjects'
      path: '/subjects'
      fullPath: '/admin/academics/subjects'
      preLoaderRoute: typeof AdminAcademicsSubjectsRouteImport
      parentRoute: typeof AdminAcademicsRoute
    }
    '/admin/academics/grade-levels': {
      id: '/admin/academics/grade-levels'
      path: '/grade-levels'
      fullPath: '/admin/academics/grade-levels'
      preLoaderRoute: typeof AdminAcademicsGradeLevelsRouteImport
      parentRoute: typeof AdminAcademicsRoute
    }
    '/admin/academics/classes': {
      id: '/admin/academics/classes'
      path: '/classes'
      fullPath: '/admin/academics/classes'
      preLoaderRoute: typeof AdminAcademicsClassesRouteImport
      parentRoute: typeof AdminAcademicsRoute
    }
    '/admin/academics/class-assignments': {
      id: '/admin/academics/class-assignments'
      path: '/class-assignments'
      fullPath: '/admin/academics/class-assignments'
      preLoaderRoute: typeof AdminAcademicsClassAssignmentsRouteImport
      parentRoute: typeof AdminAcademicsRoute
    }
  }
}

interface AdminAcademicsRouteChildren {
  AdminAcademicsClassAssignmentsRoute: typeof AdminAcademicsClassAssignmentsRoute
  AdminAcademicsClassesRoute: typeof AdminAcademicsClassesRoute
  AdminAcademicsGradeLevelsRoute: typeof AdminAcademicsGradeLevelsRoute
  AdminAcademicsSubjectsRoute: typeof AdminAcademicsSubjectsRoute
  AdminAcademicsTermsRoute: typeof AdminAcademicsTermsRoute
  AdminAcademicsTimetablesRoute: typeof AdminAcademicsTimetablesRoute
  AdminAcademicsYearsRoute: typeof AdminAcademicsYearsRoute
}

const AdminAcademicsRouteChildren: AdminAcademicsRouteChildren = {
  AdminAcademicsClassAssignmentsRoute: AdminAcademicsClassAssignmentsRoute,
  AdminAcademicsClassesRoute: AdminAcademicsClassesRoute,
  AdminAcademicsGradeLevelsRoute: AdminAcademicsGradeLevelsRoute,
  AdminAcademicsSubjectsRoute: AdminAcademicsSubjectsRoute,
  AdminAcademicsTermsRoute: AdminAcademicsTermsRoute,
  AdminAcademicsTimetablesRoute: AdminAcademicsTimetablesRoute,
  AdminAcademicsYearsRoute: AdminAcademicsYearsRoute,
}

const AdminAcademicsRouteWithChildren = AdminAcademicsRoute._addFileChildren(
  AdminAcademicsRouteChildren,
)

interface AdminRouteChildren {
  AdminAcademicsRoute: typeof AdminAcademicsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAttendanceStaffRoute: typeof AdminAttendanceStaffRoute
  AdminAttendanceStudentsRoute: typeof AdminAttendanceStudentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicsRoute: AdminAcademicsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAttendanceStaffRoute: AdminAttendanceStaffRoute,
  AdminAttendanceStudentsRoute: AdminAttendanceStudentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authProfileRoute: authProfileRoute,
  authSignUpRoute: authSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
